// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAixcveV0SWjIdScD8TtXGXcqfactYZEK0',
    appId: '1:70002321502:web:c2923617436615c7c46ccf',
    messagingSenderId: '70002321502',
    projectId: 'munevver-39d6a',
    authDomain: 'munevver-39d6a.firebaseapp.com',
    storageBucket: 'munevver-39d6a.appspot.com',
    measurementId: 'G-Q88KPXYYPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDauYGI7XENwHfiijUN8pGpWkPezHeEEo8',
    appId: '1:70002321502:android:e45640fc1dcca06ec46ccf',
    messagingSenderId: '70002321502',
    projectId: 'munevver-39d6a',
    storageBucket: 'munevver-39d6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD11KZV6hWOH4hXuN_431AOGGfEPalyso',
    appId: '1:70002321502:ios:3c6dfc658e39f3c2c46ccf',
    messagingSenderId: '70002321502',
    projectId: 'munevver-39d6a',
    storageBucket: 'munevver-39d6a.appspot.com',
    iosBundleId: 'com.example.munevver',
  );
}
